/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author 2ndyrGroupA
 */
public class Dashboards extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboards
     */
    public Dashboards() {
        initComponents();

        try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
            PreparedStatement stmt = con.prepareStatement("SELECT sum(amount) as totalsale FROM sales"); //get the connection stream(connection port)

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                totalSales.setText(rs.getString("totalsale"));
            } else {
                JOptionPane.showMessageDialog(null, "NO sales Yet");

            }
            PreparedStatement stmt2 = con.prepareStatement("SELECT count(*) as menuCount FROM menu");
            ResultSet rs2 = stmt2.executeQuery();
            if (rs2.next()) {
                totalMenu.setText(rs.getString("menuCount"));
            } else {
                JOptionPane.showMessageDialog(null, "NO Menu");
            }
            PreparedStatement stmt3 = con.prepareStatement("SELECT count(status) as orderPending FROM orders WHERE status='pending'");
            ResultSet rs3 = stmt3.executeQuery();
            if (rs3.next()) {
                pendingOrders.setText(rs.getString("orderPending"));
            } else {
                JOptionPane.showMessageDialog(null, "NO Menu");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);

        }       // TODO add your handling code here:
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        totalSales = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        totalMenu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        pendingOrders = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(740, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(740, 540));
        jPanel5.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setLayout(null);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4);
        jPanel4.setBounds(203, 26, 0, 0);

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 90, 260, 30);

        totalSales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalSales.setForeground(new java.awt.Color(240, 240, 240));
        totalSales.setText("10,500");
        jPanel3.add(totalSales);
        totalSales.setBounds(20, 20, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Total sales Today");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 50, 110, 30);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(60, 50, 260, 120);

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(null);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8);
        jPanel8.setBounds(203, 26, 0, 0);

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9);
        jPanel9.setBounds(0, 90, 260, 30);

        totalMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalMenu.setForeground(new java.awt.Color(240, 240, 240));
        totalMenu.setText("25");
        jPanel7.add(totalMenu);
        totalMenu.setBounds(20, 20, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Total Menus");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(20, 50, 110, 30);

        jPanel5.add(jPanel7);
        jPanel7.setBounds(370, 50, 260, 120);

        jPanel16.setBackground(new java.awt.Color(153, 0, 153));
        jPanel16.setLayout(null);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jPanel17);
        jPanel17.setBounds(203, 26, 0, 0);

        jPanel18.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel18);
        jPanel18.setBounds(0, 90, 260, 30);

        pendingOrders.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pendingOrders.setForeground(new java.awt.Color(240, 240, 240));
        pendingOrders.setText("10");
        jPanel16.add(pendingOrders);
        pendingOrders.setBounds(20, 20, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Pending Orders");
        jPanel16.add(jLabel8);
        jLabel8.setBounds(20, 50, 110, 30);

        jPanel5.add(jPanel16);
        jPanel16.setBounds(60, 210, 260, 120);

        jPanel25.setBackground(new java.awt.Color(204, 153, 0));
        jPanel25.setLayout(null);

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel25.add(jPanel26);
        jPanel26.setBounds(203, 26, 0, 0);

        jPanel27.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel25.add(jPanel27);
        jPanel27.setBounds(0, 90, 260, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("8/15");
        jPanel25.add(jLabel7);
        jLabel7.setBounds(20, 20, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Available Tables");
        jPanel25.add(jLabel1);
        jLabel1.setBounds(20, 50, 110, 30);

        jPanel5.add(jPanel25);
        jPanel25.setBounds(370, 210, 260, 120);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel pendingOrders;
    private javax.swing.JLabel totalMenu;
    private javax.swing.JLabel totalSales;
    // End of variables declaration//GEN-END:variables
}
