/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author 2ndyrGroupA
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginAsWaiter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        closeIcon = new javax.swing.JLabel();
        loginAsAdminr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        loginField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        loginAsWaiter.setBackground(new java.awt.Color(255, 255, 255));
        loginAsWaiter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginAsWaiter.setForeground(new java.awt.Color(0, 153, 153));
        loginAsWaiter.setText("Login as Waiter");
        loginAsWaiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAsWaiterMouseClicked(evt);
            }
        });
        loginAsWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsWaiterActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posapp/rsz_1rsz_60a3c055b18fa.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 60, 140, 160);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Point of Sales Software");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 160, 320, 90);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("P.O.S");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 90, 150, 80);

        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posapp/closeIcon.png"))); // NOI18N
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
        });
        jPanel1.add(closeIcon);
        closeIcon.setBounds(280, 0, 40, 40);

        loginAsAdminr.setBackground(new java.awt.Color(255, 255, 255));
        loginAsAdminr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginAsAdminr.setForeground(new java.awt.Color(0, 153, 153));
        loginAsAdminr.setText("Login as Admin");
        loginAsAdminr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAsAdminrMouseClicked(evt);
            }
        });
        loginAsAdminr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsAdminrActionPerformed(evt);
            }
        });
        jPanel1.add(loginAsAdminr);
        loginAsAdminr.setBounds(90, 320, 140, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 320, 400));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginField.setBackground(new java.awt.Color(0, 150, 140));
        loginField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginField.setForeground(new java.awt.Color(255, 255, 255));
        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });
        jPanel2.add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 210, 40));

        loginBtn.setBackground(new java.awt.Color(0, 150, 140));
        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 40));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 20));

        passField.setBackground(new java.awt.Color(0, 150, 140));
        passField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        jPanel2.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posapp/rsz_1rsz_1rsz_60a3c2dc461f2.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 110, 70));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Waiter Login");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 190, 69));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked

       String username= loginField.getText();
        String password= passField.getText();
        try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           try (Connection con = DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr") //establishes the connection
           ) {
               PreparedStatement stmt =con.prepareStatement("SELECT * FROM users WHERE name=? AND password=? "); //get the connection stream(connection port)
               stmt.setString(1,username);
               stmt.setString(2,password);
               ResultSet rs = stmt.executeQuery();
               if (rs.next()) {
                  WaiterDashBoard db = new WaiterDashBoard();
                   db.setVisible(true);
                   setVisible(false);       
               }
                else {
                   JOptionPane.showMessageDialog(null, "Invalid username or Password");
                   
               }
           } //get the connection stream(connection port)
       } catch (Exception e) {
           System.out.println(e);
           
           
           
       }       // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnMouseClicked

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
    System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void loginAsWaiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAsWaiterMouseClicked
       
    }//GEN-LAST:event_loginAsWaiterMouseClicked

    private void loginAsWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAsWaiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAsWaiterActionPerformed

    private void loginAsAdminrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAsAdminrMouseClicked
      adminLogin lg = new adminLogin();
        lg.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_loginAsAdminrMouseClicked

    private void loginAsAdminrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAsAdminrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAsAdminrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginAsAdminr;
    private javax.swing.JButton loginAsWaiter;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginField;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables

    void setVisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
