/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posapp;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2ndyrGroupA
 */
public class WaiterDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form WaiterDashBoard
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public WaiterDashBoard() throws ClassNotFoundException, SQLException {
        initComponents();
         id.setVisible(false);
        Status.setVisible(false);
        dispOrders();
        dispMenu();
    } 
    
    public void dispMenu(){
    try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM menu");
            ResultSet rs = stmt.executeQuery();
            Class.forName("com.mysql.jdbc.Driver");

            ResultSetMetaData stData = rs.getMetaData();

            int q = stData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) menulist.getModel();
            RecordTable.setRowCount(0);

            while (rs.next()) {
                Vector columnData = new Vector();
                int i;

                for (i = 1; i <= q; i++) {
                  
                    columnData.add(rs.getString("menuname"));
                    columnData.add(rs.getString("price"));
                  

                }
                RecordTable.addRow(columnData);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    
    
    
    
    }
    
    
    
    
 public void dispOrders() throws ClassNotFoundException, SQLException {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM orders");
            ResultSet rs = stmt.executeQuery();
            Class.forName("com.mysql.jdbc.Driver");

            ResultSetMetaData stData = rs.getMetaData();

            int q = stData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) transactionList.getModel();
            RecordTable.setRowCount(0);

            while (rs.next()) {
                Vector columnData = new Vector();
                int i;

                for (i = 1; i <= q; i++) {
                    columnData.add(rs.getString("id"));
                    columnData.add("0" + rs.getString("tableno"));
                    columnData.add(rs.getString("item"));
                    columnData.add(rs.getString("quantity"));
                    columnData.add(rs.getString("price"));
                    columnData.add(rs.getString("subtotal"));
                    columnData.add(rs.getString("status"));

                }
                RecordTable.addRow(columnData);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionList = new javax.swing.JTable();
        SearchBtn = new javax.swing.JButton();
        searchTableNum = new javax.swing.JTextField();
        tablenum = new javax.swing.JTextField();
        menuname = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddOrder = new javax.swing.JButton();
        CancelOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        payOrder = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        deliverOrder = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TableCount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        menulist = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1020, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(1030, 520));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(0, 153, 153));

        transactionList.setBackground(new java.awt.Color(0, 153, 153));
        transactionList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        transactionList.setForeground(new java.awt.Color(255, 255, 255));
        transactionList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Table Number", "Menu Name", "Price", "Quanity", "Subtotal", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        transactionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transactionList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 510, 240));

        SearchBtn.setBackground(new java.awt.Color(0, 51, 51));
        SearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBtn.setText("Search");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 90, 40));

        searchTableNum.setText("Search orders by table number...");
        searchTableNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTableNumActionPerformed(evt);
            }
        });
        searchTableNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTableNumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTableNumKeyReleased(evt);
            }
        });
        jPanel1.add(searchTableNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 210, 40));
        jPanel1.add(tablenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 38));
        jPanel1.add(menuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 38));
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, 38));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Table no.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 79, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Menu name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 79, -1));

        AddOrder.setBackground(new java.awt.Color(0, 51, 51));
        AddOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddOrder.setForeground(new java.awt.Color(255, 255, 255));
        AddOrder.setText("Add Order");
        AddOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddOrderMouseClicked(evt);
            }
        });
        jPanel1.add(AddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 40));

        CancelOrder.setBackground(new java.awt.Color(0, 51, 51));
        CancelOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CancelOrder.setForeground(new java.awt.Color(255, 255, 255));
        CancelOrder.setText("Cancel Order");
        CancelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelOrderMouseClicked(evt);
            }
        });
        jPanel1.add(CancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Total Bill");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Php");

        payOrder.setBackground(new java.awt.Color(0, 51, 51));
        payOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payOrder.setForeground(new java.awt.Color(255, 255, 255));
        payOrder.setText("Settle Payment");
        payOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 230, 120));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 38));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Price");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 79, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Php");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 41, -1));

        deliverOrder.setBackground(new java.awt.Color(0, 51, 51));
        deliverOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deliverOrder.setForeground(new java.awt.Color(255, 255, 255));
        deliverOrder.setText("Deliver Order");
        deliverOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliverOrderMouseClicked(evt);
            }
        });
        jPanel1.add(deliverOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 38));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 80, 38));
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, 38));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Table Number: ");

        TableCount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TableCount.setForeground(new java.awt.Color(255, 255, 255));
        TableCount.setText("0");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableCount)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TableCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Quantity");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 79, -1));

        jPanel12.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 750, 450));

        menulist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menulist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(menulist);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, 360));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Menu List");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 40));

        jPanel7.setBackground(new java.awt.Color(25, 68, 68));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posapp/rsz_1rsz_60a646201b470.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Waiter");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 712, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionListMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel) transactionList.getModel();
        int SelectedRows = transactionList.getSelectedRow();

        id.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        tablenum.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        menuname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        qty.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        price.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        Status.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
    }//GEN-LAST:event_transactionListMouseClicked

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
         DefaultTableModel model = (DefaultTableModel) transactionList.getModel();
        javax.swing.table.TableRowSorter<DefaultTableModel> tr = new javax.swing.table.TableRowSorter<DefaultTableModel>(model);
        transactionList.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTableNum.getText().trim()));
        
      
        TableCount.setText(searchTableNum.getText());
        
       
       int tblnum = parseInt(searchTableNum.getText().substring(1));
       
        try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
           PreparedStatement stmt =con.prepareStatement("SELECT sum(subtotal) as totalBill FROM orders WHERE status='delivered' and tableno=?"); //get the connection stream(connection port)
           stmt.setInt(1,tblnum);
       
            ResultSet rs = stmt.executeQuery();
             if (rs.next()) {
                   
                total.setText(rs.getString("totalBill"));
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or Password");
                  
                }
           
           
       
           con.close();
       } catch (Exception e) {
           System.out.println(e);
           
           
           
       }       // TODO add your handling code here:

    }//GEN-LAST:event_SearchBtnMouseClicked

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed

    }//GEN-LAST:event_SearchBtnActionPerformed

    private void searchTableNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTableNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTableNumActionPerformed

    private void searchTableNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTableNumKeyPressed

    }//GEN-LAST:event_searchTableNumKeyPressed

    private void searchTableNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTableNumKeyReleased

    }//GEN-LAST:event_searchTableNumKeyReleased

    private void AddOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddOrderMouseClicked
        int table_num = parseInt(tablenum.getText());
        String menuName = menuname.getText();
        int Price = parseInt(price.getText());
        int quantity = parseInt(qty.getText());
        int subtotal = Price * quantity;
        String Status = "Pending";
        if (table_num != 0 || menuName != "" || Price != 0 || quantity != 0) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
                PreparedStatement stmt = con.prepareStatement("INSERT INTO orders(tableno,item,quantity,price,subtotal,status) values(?,?,?,?,?,?)");
                stmt.setInt(1, table_num);
                stmt.setString(2, menuName);
                stmt.setInt(3, quantity);
                stmt.setInt(4, Price);
                stmt.setInt(5, subtotal);
                stmt.setString(6, Status);

                stmt.executeUpdate();
                dispOrders();
                JOptionPane.showMessageDialog(this, "Order Added");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "All field must not be empty");
        }
    }//GEN-LAST:event_AddOrderMouseClicked

    private void CancelOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelOrderMouseClicked
        int ID = parseInt(id.getText());
        if (ID != 0) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
                PreparedStatement stmt = con.prepareStatement("DELETE FROM orders where id=?");
                stmt.setInt(1, ID);

                //
                stmt.executeUpdate();
                dispOrders();
                JOptionPane.showMessageDialog(this, "Order deleted Successfully");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must select an Order");

        }
    }//GEN-LAST:event_CancelOrderMouseClicked

    private void payOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payOrderMouseClicked

        int bill = parseInt(total.getText());
        int tblnum = parseInt(TableCount.getText());
        if (bill!=0 && tblnum!=0){

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
                PreparedStatement stmt = con.prepareStatement("INSERT INTO sales(tableno,amount) values(?,?)");
                stmt.setInt(1, tblnum);
                stmt.setInt(2, bill);
                //stmt.setInt(3, Price);
                //

                stmt.executeUpdate();
                dispOrders();

                PreparedStatement stmt2 = con.prepareStatement("DELETE FROM orders WHERE tableno=? and status=?");
                stmt2.setInt(1, tblnum);
                stmt2.setString(2,"Delivered");
                stmt2.executeUpdate();
                dispOrders();
                JOptionPane.showMessageDialog(this, "Sales Added");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No delivered Items selected");
        }
    }//GEN-LAST:event_payOrderMouseClicked

    private void deliverOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliverOrderMouseClicked
        int ID = parseInt(id.getText());
        if (ID != 0) {
            if (Status.getText() != "pending") {

                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://remotemysql.com/i6jPHFJtKc", "i6jPHFJtKc", "WGD2ufVrPr"); //establishes the connection
                    PreparedStatement stmt = con.prepareStatement("UPDATE orders SET status=? where id=?");
                    stmt.setString(1, "Delivered");
                    stmt.setInt(2, ID);
                    //

                    stmt.executeUpdate();
                    dispOrders();
                    JOptionPane.showMessageDialog(this, "Order Delivered");

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Order still Pending!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must select an Order");
        }
    }//GEN-LAST:event_deliverOrderMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        login lg=new login();
        lg.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrder;
    private javax.swing.JButton CancelOrder;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField Status;
    private javax.swing.JLabel TableCount;
    private javax.swing.JButton deliverOrder;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable menulist;
    private javax.swing.JTextField menuname;
    private javax.swing.JButton payOrder;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField searchTableNum;
    private javax.swing.JTextField tablenum;
    private javax.swing.JTextField total;
    private javax.swing.JTable transactionList;
    // End of variables declaration//GEN-END:variables

   
}
